export const TRAER_DOCUMENTO = 'TRAER_DOCUMENTO';
export const TRAER_DOCUMENTO_EXITO = 'TRAER_DOCUMENTO_EXITO';
export const TRAER_DOCUMENTO_ERROR = 'TRAER_DOCUMENTO_ERROR';

export const OBTENER_DOCUMENTO_ELIMINAR = 'OBTENER_DOCUMENTO_ELIMINAR';
export const DOCUMENTO_ELIMINADO_EXITO = 'DOCUMENTO_ELIMINADO_EXITO';
export const DOCUMENTO_ELIMINADO_ERROR = 'DOCUMENTO_ELIMINADO_ERROR';